export const ADD_FAVORITE_TAGS = 'ADD_FAVORITE_TAGS';
export const UPDATE_FAVORITE_TAGS = 'UPDATE_FAVORITE_TAGS';
export const DEL_FAVORITE_TAGS = 'DEL_FAVORITE_TAGS';
export const DEL_ALL_TAGS = 'DEL_ALL_TAGS';